# Generated by Django 4.1.3 on 2022-12-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='d', upload_to='pics'),
            preserve_default=False,
        ),
    ]
